version: 2.1

workflows:
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:202008-01
jobs:
  build:
    machine:
      image: ubuntu-2004:202008-01
      docker_layer_caching: true

    steps:
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version

      - checkout

      - run:
          name: build locally client-security-starter
          command: |
            git clone https://github.com/mrFlick72/client-security-starter.git
            cd client-security-starter
            mvn clean install

      - run: mvn clean install -T2C

      - run:
          name: docker push
          command: |
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker build . -t mrflick72/family-budget-website-k8s:latest
            docker push mrflick72/family-budget-website-k8s:latest