name: build

on:
  push: { }
  workflow_dispatch: { }

jobs:
  provisioning:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: install openjdk
        run: |
          sudo apt-get update && sudo apt-get install openjdk-17-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
          java -version

      - name: build testing environment
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

          git clone https://github.com/mrFlick72/client-security-starter.git
          cd client-security-starter
          mvn clean install -q

      - name: Build
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          mvn clean install

      - name: docker push
        run: |
          if [[ ${GITHUB_REF##*/} == 'master' ]]
          then
            DOCKER_TAG="latest"
          else
            DOCKER_TAG="${GITHUB_REF##*/}"
          fi
          echo "$DOCKER_TAG"
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build . -t mrflick72/family-budget-website-k8s:$DOCKER_TAG
          docker push mrflick72/family-budget-website-k8s:$DOCKER_TAG
